services:
  # app:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  docmost:
    image: docker.io/styskin/manulai:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: '${APP_URL}'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      MANUL_AGENTS_URL: 'http://manul_agent:8000'
      MAIL_DRIVER: smtp
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      MAIL_FROM_ADDRESS: no-reply@manul.ai
      MAIL_FROM_NAME: Manul.ai
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  phoenix:
    image: arizephoenix/phoenix:version-10.2.1
    restart: unless-stopped
    ports:
      - "6006:6006"  # PHOENIX_PORT
      - "4317:4317"  # PHOENIX_GRPC_PORT
    environment:
      PHOENIX_WORKING_DIR: /mnt/data
      PHOENIX_ENABLE_AUTH: true
      PHOENIX_SECRET: ${PHOENIX_SECRET}
    volumes:
      - phoenix_data:/mnt/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  manul_agent:
    image: docker.io/phoenix120/manul_agents:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'postgresql+asyncpg://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public'
      MCP_SERVER: 'docmost:3000'
    volumes:
      - manul_agent:/logs

volumes:
  docmost:
  db_data:
  redis_data:
  phoenix_data:
  manul_agent:
