name: Docker Compose CICD

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run:
          docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/manulai:$(date +%s) --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/manulai:latest --push

  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    environment: secrets
    steps:
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/docmost/
          docker-compose down
          docker-compose pull
          docker-compose up -d 
