name: Docker Compose CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/styskin/manulai:$(date +%s) --tag docker.io/styskin/manulai:latest

  deployment:
    runs-on: ubuntu-latest
    environment: secret
    steps:
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/docmost/
          docker-compose down
          docker-compose up --pull -d 
